"""create original tables

Revision ID: d0c1cb58c2b3
Revises: 
Create Date: 2022-08-18 19:19:11.476136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c1cb58c2b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ckimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('ck_number', sa.String(), nullable=True),
    sa.Column('alt_number', sa.String(), nullable=True),
    sa.Column('payee_img_as_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('payee_img_mode', sa.String(), nullable=True),
    sa.Column('payee_img_width', sa.Integer(), nullable=True),
    sa.Column('payee_img_height', sa.Integer(), nullable=True),
    sa.Column('payee_img_path', sa.String(), nullable=True),
    sa.Column('payee_txt_hugginface', sa.String(), nullable=True),
    sa.Column('payee_txt_textract', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('other1', sa.String(), nullable=True),
    sa.Column('other2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ckimage')
    op.drop_table('client')
    # ### end Alembic commands ###
