"""column client name

Revision ID: db7e4a825f1e
Revises: d0c1cb58c2b3
Create Date: 2022-08-18 23:19:26.622807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7e4a825f1e'
down_revision = 'd0c1cb58c2b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ckimage', sa.Column('client_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ckimage', 'client_name')
    # ### end Alembic commands ###
